server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - name: Hystrix
              args:
                name: productFallbackCommand
                fallbackUri: forward:/fallback/product

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health